# Generated by Django 4.2 on 2026-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
