# Generated by Django 4.2 on 2026-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reel_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
