# Generated by Django 4.2.7 on 2026-03-28 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_userprofile_profile_photo_commentreply_savedpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_reels', models.IntegerField(default=0)),
                ('new_reels', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('new_comments', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('new_votes', models.IntegerField(default=0)),
                ('total_follows', models.IntegerField(default=0)),
                ('new_follows', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('paid_subscriptions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Metrics',
                'verbose_name_plural': 'Platform Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Selfie Star', max_length=100)),
                ('platform_description', models.TextField(default='Social media platform for creators')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('max_file_size_mb', models.IntegerField(default=50)),
                ('allowed_video_formats', models.CharField(default='mp4,mov,avi', max_length=200)),
                ('allowed_image_formats', models.CharField(default='jpg,jpeg,png,gif', max_length=200)),
                ('max_caption_length', models.IntegerField(default=2200)),
                ('enable_comments', models.BooleanField(default=True)),
                ('enable_voting', models.BooleanField(default=True)),
                ('auto_moderation', models.BooleanField(default=False)),
                ('profanity_filter', models.BooleanField(default=True)),
                ('spam_detection', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cdn_enabled', models.BooleanField(default=False)),
                ('cdn_url', models.URLField(blank=True, null=True)),
                ('api_rate_limit', models.IntegerField(default=100, help_text='Requests per minute')),
                ('api_enabled', models.BooleanField(default=True)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('track_user_activity', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('security', 'Security')], max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_systeml_created_d96280_idx'), models.Index(fields=['log_type'], name='api_systeml_log_typ_449bff_idx')],
            },
        ),
    ]
