# Generated by Django 4.2.7 on 2026-03-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_adminnotification_platformmetrics_platformsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('prize_title', models.CharField(max_length=200)),
                ('prize_description', models.TextField()),
                ('prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('voting', 'Voting Phase'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('min_followers', models.IntegerField(default=0, help_text='Minimum followers required')),
                ('min_level', models.IntegerField(default=1, help_text='Minimum user level required')),
                ('min_votes_per_reel', models.IntegerField(default=0, help_text='Minimum votes per reel to qualify')),
                ('required_hashtags', models.CharField(blank=True, help_text='Comma-separated hashtags', max_length=500)),
                ('start_date', models.DateTimeField()),
                ('entry_deadline', models.DateTimeField(help_text='Deadline for submitting entries')),
                ('voting_start', models.DateTimeField(help_text='When voting begins')),
                ('voting_end', models.DateTimeField(help_text='When voting ends')),
                ('winner_count', models.IntegerField(default=1, help_text='Number of winners')),
                ('winners_announced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('disqualification_reason', models.TextField(blank=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.campaign')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='api.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_count', '-submitted_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_campaign', 'New Campaign'), ('entry_approved', 'Entry Approved'), ('voting_started', 'Voting Started'), ('winner_announced', 'Winner Announced'), ('prize_ready', 'Prize Ready')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='1st, 2nd, 3rd place, etc.')),
                ('prize_claimed', models.BooleanField(default=False)),
                ('prize_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='api.campaign')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_records', to='api.campaignentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('campaign', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='CampaignVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.campaignentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
