# Generated by Django 4.2.7 on 2026-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_campaign_campaignentry_campaignnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_activity',
            field=models.BooleanField(default=True),
        ),
    ]
