# Generated by Django 4.2 on 2026-04-03 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coins', models.IntegerField()),
                ('bonus_coins', models.IntegerField(default=0)),
                ('price_etb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_etb'],
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='entry_deadline',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_entries',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='voting_end',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='voting_start',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('daily', 'Daily Reward'), ('weekly', 'Weekly Reward'), ('monthly', 'Monthly Reward'), ('grand_finale', 'Grand Finale'), ('flash', 'Flash Challenge')], default='grand_finale', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='consistency_weight',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creativity_weight',
            field=models.IntegerField(blank=True, default=30, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaign',
            name='engagement_weight',
            field=models.IntegerField(blank=True, default=25, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='judge_weight',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_entries_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_winners',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='campaign',
            name='official_hashtag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='original_content_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='public_vote_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='quality_weight',
            field=models.IntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='theme_weight',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget in ETB', max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='prize_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='prize_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('vip', 'VIP')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_reference', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('vip', 'VIP')], default='free', max_length=10)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('daily_posts_used', models.IntegerField(default=0)),
                ('daily_posts_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Coin Accounts',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('cash', 'Cash Prize'), ('phone', 'Smartphone'), ('airtime', 'Airtime'), ('data', 'Data Bundle'), ('voucher', 'Voucher'), ('trip', 'Trip'), ('brand_deal', 'Brand Deal'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('rank', models.IntegerField(help_text='1 for 1st place, 2 for 2nd place, etc.')),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.campaign')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', 'campaign'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('earned', 'Earned'), ('spent', 'Spent'), ('bonus', 'Bonus'), ('refund', 'Refund')], max_length=10)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
