# Generated by Django 4.2 on 2026-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_campaign_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_lifecycle',
            field=models.BooleanField(default=True, help_text='Auto transition upcoming->active->voting->completed'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='coin_gift_points',
            field=models.IntegerField(default=2, help_text='Points per coin gift sent'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='comment_points',
            field=models.IntegerField(default=3, help_text='Points per comment received'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='completion_bonus',
            field=models.IntegerField(default=50, help_text='Bonus for completing all days in period'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='daily_random_pct',
            field=models.IntegerField(default=30, help_text='% winners by random (Daily campaigns)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='daily_score_pct',
            field=models.IntegerField(default=70, help_text='% winners by score (Daily campaigns)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='inactivity_penalty',
            field=models.IntegerField(default=5, help_text='Points deducted per inactive day'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='like_points',
            field=models.IntegerField(default=2, help_text='Points per like received'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_bonus_points',
            field=models.IntegerField(default=1, help_text='Points for daily login'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='once_per_cycle',
            field=models.BooleanField(default=True, help_text='User can only win once per campaign cycle'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='share_points',
            field=models.IntegerField(default=5, help_text='Points per share'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='spin_reward_points',
            field=models.IntegerField(default=5, help_text='Points from daily spin'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='streak_bonus',
            field=models.IntegerField(default=10, help_text='Bonus points per consecutive day posted'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='streak_multiplier_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voting_start_date',
            field=models.DateTimeField(blank=True, help_text='When voting phase begins (Grand campaigns)', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('voting', 'Voting'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
