export const THEME = {
  pri:"#DA9B2A",
  priD:"#B8821E",
  priL:"#FDF6E7",
  sec:"#1B4332",
  secL:"#D1FAE5",
  secM:"#6EE7B7",
  acc:"#C0392B",
  accL:"#FDEAEA",
  gold:"#F59E0B",
  goldL:"#FFFBEB",
  grn:"#10B981",
  grnL:"#D1FAE5",
  blu:"#3B82F6",
  bluL:"#DBEAFE",
  org:"#F97316",
  orgL:"#FFF7ED",
  purple:"#7C3AED",
  purpleL:"#EDE9FE",
  red:"#EF4444",
  redL:"#FEE2E2",
  bg:"#FAFAF7",
  card:"#FFFFFF",
  txt:"#1C1917",
  sub:"#78716C",
  border:"#E7E5E4",
  dark:"#0C1A12",
};

export const PLANS = [
  {
    id:"free",
    name:"Explorer",
    am:"ተመራማሪ",
    emoji:"🌱",
    price:"Free",
    period:"",
    color:"#10B981",
    popular:false,
    features:["1 post/day","Basic analytics","Community access"]
  },
  {
    id:"pro",
    name:"Star",
    am:"ኮከብ",
    emoji:"⭐",
    price:"$4.99",
    period:"/mo",
    color:"#DA9B2A",
    popular:true,
    features:["Unlimited posts","Advanced analytics","Priority support","Monetization"]
  },
  {
    id:"premium",
    name:"Legend",
    am:"ታላቅ",
    emoji:"👑",
    price:"$9.99",
    period:"/mo",
    color:"#7C3AED",
    popular:false,
    features:["Everything in Star","Custom branding","Direct messaging","Exclusive events"]
  },
];
